### ISSUE TITLE
APP更新问题

### ISSUE THREAD

**Issue by AmadeusGhost** [openjmu/OpenJMU#170]
打开OpenJMU，提示更新，下载完apk包后没有弹出安装页面。

**Comment by AlexVincent525** [comment]
Fixed by https://github.com/openjmu/OpenJMU/commit/232e8ad2e8d4027675eb6c80d45e04bd61095da3 .

**Comment by Evsio0n** [comment]
@AlexVincent525 Still have issue when updating with OnePlus. Please do not close the issue.

**Comment by AlexVincent525** [comment]
> @AlexVincent525 Still have issue when updating with OnePlus. Please do not close the issue.

The issue about OnePlus device update is another case. Please track it in a new issue.
